### ISSUE TITLE
Couldn't find preset "@babel/preset-env"

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [suren-atoyan/monaco-loader#18]
When I add `"@monaco-editor/loader": "1.2.0"` to my package.json and try to run the application (via `grunt auto-build`), I receive the following error:
`Error: Couldn't find preset "@babel/preset-env" relative to directory "<project>/node_modules/@monaco-editor/loader" while parsing file: <project>/node_modules/@monaco-editor/loader/lib/cjs/index.js`

I have `"babel-preset-env": "^1.6.1"` in my dependencies. Any idea what I am missing?

**Comment by suren-atoyan** [comment]
Hey @Adrian-Bielefeldt 👋 

I guess `babel-preset-env` and `@babel/preset-env` are incompatible. Your dev setup seems pretty outdated, am I right?
