### ISSUE TITLE
Does this package work with https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin?

### ISSUE THREAD

**Issue by wegry** [suren-atoyan/monaco-loader#28]
It seems like the `languages` option of `monaco-editor-webpack-plugin@7.0.1` doesn't have `languages` respected. If just typescript and javascript are set, all languages are being output with ~in~ version `@monaco-editor/react@4.4.6`.

```typescript
import * as monaco from "monaco-editor";
import { loader } from "@monaco-editor/react";

loader.config({ monaco });

// ...
```

**Comment by suren-atoyan** [comment]
@wegry what exactly does `all languages are being output with in ...` mean?

**Comment by wegry** [comment]
@suren-atoyan php, mysql, yaml, etc. are all included.

**Comment by wegry** [comment]
Using 

```diff
- import * as Monaco from 'monaco-editor';
+ import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
```

for importing Monaco seems work when the only languages in my output I'd like to include are TS and JS.
