### ISSUE TITLE
Revert icon not work in some cases on monaco-diff-editor using 0.36.1 cdn version

### ISSUE THREAD

**Issue by sourabh-singla** [suren-atoyan/monaco-loader#31]
Issue: Revert icon not work in some cases on monaco-diff-editor

I tried it using latest version and on that it is working. Attaching video recording for reference.
We have to update https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs to 0.38.0 i.e latest version

https://github.com/suren-atoyan/monaco-loader/assets/129030391/17730045-7bbd-45ec-9c02-580c04e699de

Attached monaco editor link where you can find this issue
https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAIgBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw5U5qQueZ-_oZV7pPg_ICTNUlZ0aFnSg-Rf-7glw9kvLEwU9DUBv61vfTQgkbnA_UZImSVzLZfYENGzweQwl2WpWkekBDUDPvXXh0Hk7w9OCIYDR_qHmPdWfkn449HPCerL8aahZpzTRsPE-nwEaMfejQQvCSFVie6D10gCtXST1XJJoGxbqsxrMKHlHUM-a0q_kuVip-Sl7JTKl1pnJ4HRV7ct4JM6CIzRuuhOU9YWWNgrmHnEr-iMGq63ePrx51pxiyRj4O_CPsk7ziMbP4tjgbNHsIzBYVFtazHJtRP62qxY66O_6fGQBqQij_T2rj9mTCiDROY6K4ZtGWGaA7dUOXq3zEGNZE24MVT0o2HL-fdNN-wcfgWNbr9x5stsQCJMLjBQ4sGTruJW7wEGSOgSAMd9BjF4_NjpMZ2EKxy0hwiUWp4tZwWL2VrpgGwthplAn_byQNDQD77eX-gzS_Revghi7bRZl-VjDOinhPEo31GCGin-DDirE-F3CthcxIXf-lVtXW

**Comment by suren-atoyan** [comment]
@sourabh-singla you can configure it and use the latest version - https://github.com/suren-atoyan/monaco-loader#config

**Comment by suren-atoyan** [comment]
I am closing this because it's already uses newer version
